CREATE TABLE "Customer" (
  "Index" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "User_Id" varchar(8) UNIQUE,
  "Name" varchar(64),
  "Email" varchar(256) UNIQUE,
  "Password" varchar(256),
  "created_at" timestamp
);

CREATE TABLE "Order" (
  "Order_Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "User_Id" varchar(8) NOT NULL,
  "Date" timestamp,
  "Status" varchar NOT NULL,
  "Amount" decimal(10,2)
);

CREATE TABLE "Order_Item" (
  "Order_Item_Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Order_Id" integer,
  "Product_Id" varchar(8),
  "Quantity" integer,
  "Amount" decimal(10,2)
);

CREATE TABLE "Product" (
  "Index" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Product_Id" varchar(8) UNIQUE,
  "Name" varchar,
  "Description" text,
  "Price" decimal(10,2),
  "Photo_Id" varchar,
  "Category_Id" integer,
  "created_at" timestamp
);

CREATE TABLE "Stock" (
  "Stock_Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Product_Id" varchar(8) NOT NULL,
  "Quantity" integer,
  "Last_Updated" timestamp
);

CREATE TABLE "Category" (
  "Category_Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Name" varchar,
  "Description" text,
  "Photo_Id" varchar
);

CREATE TABLE "Cart" (
  "Cart_Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "User_Id" varchar(8) NOT NULL,
  "Status" varchar NOT NULL,
  "created_at" timestamp
);

CREATE TABLE "CartItem" (
  "Cart_Item_Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Cart_Id" integer NOT NULL,
  "Product_Id" varchar(8) NOT NULL,
  "Quantity" integer
);

CREATE TABLE "Payment" (
  "Payment_Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Order_Id" integer NOT NULL,
  "User_Id" varchar(8) NOT NULL,
  "Type" varchar,
  "Amount" decimal(10,2),
  "Status" varchar
);

ALTER TABLE "Order" ADD FOREIGN KEY ("User_Id") REFERENCES "Customer" ("User_Id");

ALTER TABLE "Order_Item" ADD FOREIGN KEY ("Order_Id") REFERENCES "Order" ("Order_Id");

ALTER TABLE "Cart" ADD FOREIGN KEY ("User_Id") REFERENCES "Customer" ("User_Id");

ALTER TABLE "CartItem" ADD FOREIGN KEY ("Cart_Id") REFERENCES "Cart" ("Cart_Id");

ALTER TABLE "Payment" ADD FOREIGN KEY ("User_Id") REFERENCES "Customer" ("User_Id");

ALTER TABLE "Payment" ADD FOREIGN KEY ("Order_Id") REFERENCES "Order" ("Order_Id");

ALTER TABLE "Order_Item" ADD FOREIGN KEY ("Product_Id") REFERENCES "Product" ("Product_Id");

ALTER TABLE "Product" ADD FOREIGN KEY ("Category_Id") REFERENCES "Category" ("Category_Id");

ALTER TABLE "Stock" ADD FOREIGN KEY ("Product_Id") REFERENCES "Product" ("Product_Id");
